### PR TITLE
 5 yearly ownership cost analysis

### PR DESCRIPTION
**Pull request by ekfrib23**
added 5 yearly ownership cost to main branch. Edmunds csv files in Resources folder 
analysis_5year_ownership_all.ipynb contains the analysis of the cvs data.

### CODE REVIEW

**Comment by ekfrib23** [comment]
removed data in  wrong data set

**Comment by ekfrib23** [comment]
removed data in wrong data set

**Comment by ekfrib23** [comment]
removed data in wrong data set

**Comment by ekfrib23** [comment]
removed data in wrong data set

**Comment by ekfrib23** [comment]
removed data in wrong data set

Sorry not doing this correctly

**Review by Rbusman — APPROVED** [review]

**Pull request merged**
